<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    public function run(): void
    {
        $author = User::first();
        $postCategories = Category::byType('post')->pluck('id');

        if (!$author || $postCategories->isEmpty()) {
            $this->command->warn('No author or post categories found. Run UserSeeder and CategorySeeder first.');
            return;
        }

        $posts = [
            [
                'title' => 'Tips Memilih Lokasi Billboard yang Tepat untuk Bisnis Anda',
                'content' => "Memilih lokasi billboard yang tepat adalah salah satu keputusan paling penting dalam strategi pemasaran outdoor. Berikut adalah tips yang perlu Anda perhatikan:\n\n1. **Analisis Lalu Lintas**\nPastikan lokasi billboard memiliki volume lalu lintas yang tinggi, baik kendaraan maupun pejalan kaki. Semakin banyak mata yang melihat, semakin efektif iklan Anda.\n\n2. **Target Audiens**\nSesuaikan lokasi dengan target pasar Anda. Misalnya, jika target Anda adalah profesional muda, pilih billboard di kawasan bisnis atau perkantoran.\n\n3. **Visibilitas**\nPastikan billboard tidak terhalang oleh pohon, bangunan, atau reklame lain. Jarak pandang minimal 50 meter sangat ideal.\n\n4. **Pencahayaan**\nBillboard dengan pencahayaan LED atau neon akan efektif 24 jam. Jangan remehkan exposure di malam hari.\n\n5. **Regulasi**\nPastikan billboard memiliki izin yang lengkap. Bekerjasamalah dengan penyedia jasa reklame profesional untuk mengurus perizinan.\n\nDengan mempertimbangkan faktor-faktor di atas, investasi billboard Anda akan memberikan ROI yang maksimal.",
                'category_index' => 0,
            ],
            [
                'title' => 'Keuntungan Menggunakan Neon Box untuk Brand Anda',
                'content' => "Neon box adalah media reklame yang menggunakan tabung gas neon atau lampu LED untuk menghasilkan efek cahaya yang menarik. Berikut adalah keuntungan menggunakan neon box:\n\n**Tahan Lama**\nNeon box modern dengan teknologi LED dapat bertahan hingga 50.000 jam atau sekitar 5-6 tahun penggunaan terus menerus.\n\n**Biaya Operasional Rendah**\nKonsumsi listrik LED sangat efisien, hanya sekitar 30-40% dari lampu neon konvensional.\n\n**Desain Fleksibel**\nNeon box dapat dibentuk dalam berbagai ukuran, warna, dan desain sesuai kebutuhan brand Anda.\n\n**Visibilitas 24 Jam**\nDengan pencahayaan yang terang, neon box tetap efektif di malam hari, memberikan exposure terus menerus.\n\n**Kesan Premium**\nNeon box memberikan kesan profesional dan premium yang meningkatkan brand image di mata konsumen.\n\nPilih neon box untuk solusi reklame yang elegan dan efektif untuk bisnis Anda.",
                'category_index' => 2,
            ],
            [
                'title' => 'Perbedaan Billboard, Baliho, dan Videotron',
                'content' => "Dalam dunia reklame outdoor, ada beberapa jenis media yang sering digunakan. Berikut perbedaannya:\n\n**Billboard**\n- Ukuran besar (4x6m hingga 10x20m)\n- Material vinyl atau kain\n- Dipasang secara permanen di struktur khusus\n- Untuk kampanye jangka panjang (3-12 bulan)\n\n**Baliho**\n- Ukuran besar, mirip billboard\n- Bersifat temporer\n- Pemasangan lebih sederhana\n- Untuk event atau promosi singkat (1-4 minggu)\n\n**Videotron**\n- Layar LED digital\n- Dapat menampilkan video bergerak\n- Konten dapat diubah kapan saja\n- Biaya lebih tinggi, tapi lebih interaktif\n\n**Neon Box**\n- Menggunakan pencahayaan internal\n- Ukuran bervariasi\n- Cocok untuk identitas brand\n- Efektif siang dan malam\n\nPilih media yang sesuai dengan kebutuhan kampanye dan anggaran Anda.",
                'category_index' => 3,
            ],
            [
                'title' => 'Strategi Pemasaran dengan Media Luar Ruang di Era Digital',
                'content' => "Di era digital, media luar ruang (Out-of-Home/OOH) justru semakin relevan. Berikut strategi yang bisa Anda terapkan:\n\n**1. Integrasi Digital**\nGunakan QR code atau NFC pada billboard untuk menghubungkan audiens ke landing page atau media sosial Anda.\n\n**2. Data-Driven**\nGunakan data lalu lintas dan demografi untuk memilih lokasi yang paling strategis.\n\n**3. Programmatic OOH**\nManfaatkan teknologi programmatic untuk mengelola jadwal tayang iklan videotron secara real-time.\n\n**4. Creative Content**\nBuat konten yang kreatif dan memorable. Iklan outdoor yang unik akan menjadi viral di media sosial.\n\n**5. Multi-Channel**\nKombinasikan OOH dengan kampanye digital untuk hasil maksimal. Contohnya, billboard + Instagram ads.\n\nMedia luar ruang tetap menjadi salah satu channel pemasaran paling efektif jika dikelola dengan strategi yang tepat.",
                'category_index' => 0,
            ],
            [
                'title' => 'Panduan Lengkap Sewa Billboard untuk Pemula',
                'content' => "Baru pertama kali menyewa billboard? Berikut panduan lengkapnya:\n\n**1. Tentukan Tujuan**\nApa tujuan Anda? Brand awareness, promosi produk, atau event? Tujuan akan menentukan lokasi dan durasi sewa.\n\n**2. Pilih Lokasi**\nSesuaikan dengan target audiens. Billboard di pusat kota lebih mahal tapi exposure lebih besar.\n\n**3. Tentukan Ukuran**\nUkuran standar: 4x6m, 5x10m, 8x12m. Semakin besar, semakin mahal.\n\n**4. Durasi Sewa**\nMinimal sewa biasanya 3 bulan. Semakin panjang durasi, biasanya ada diskon.\n\n**5. Biaya Produksi**\nSelain biaya sewa, ada biaya cetak/desain vinyl. Budgetkan Rp 1-3 juta untuk cetak.\n\n**6. Perizinan**\nPastikan billboard memiliki izin reklame. Penyedia jasa terpercaya akan mengurus ini.\n\n**7. Evaluasi**\nPantau performa billboard Anda. Hitung ROI berdasarkan peningkatan traffic, penjualan, atau brand awareness.\n\nDengan panduan ini, Anda siap memulai kampanye billboard pertama Anda!",
                'category_index' => 3,
            ],
            [
                'title' => 'Tren Reklame Digital di Tahun 2026',
                'content' => "Tahun 2026 membawa perubahan signifikan dalam industri reklame. Berikut tren yang perlu Anda ketahui:\n\n**1. DOOH (Digital Out-of-Home)**\nVideotron dan billboard digital semakin mendominasi. Konten dapat diubah secara real-time.\n\n**2. AI-Powered Advertising**\nKecerdasan buatan digunakan untuk menargetkan iklan berdasarkan waktu, cuaca, dan demografi.\n\n**3. Interactive Billboards**\nBillboard interaktif dengan layar sentuh dan sensor gerak yang melibatkan audiens.\n\n**4. Sustainability**\nMedia reklame ramah lingkungan dengan material daur ulang dan LED hemat energi.\n\n**5. Programmatic OOH**\nPembelian slot iklan secara otomatis melalui platform digital.\n\n**6. Hyperlocal Targeting**\nIklan yang ditargetkan secara spesifik berdasarkan lokasi geografis.\n\nTetap update dengan tren terbaru untuk memaksimalkan efektivitas kampanye reklame Anda.",
                'category_index' => 1,
            ],
            [
                'title' => 'Harga Sewa Billboard di Jakarta dan sekitarnya 2026',
                'content' => "Berapa biaya sewa billboard di Jakarta? Harga sewa billboard bervariasi tergantung lokasi, ukuran, dan durasi sewa. Berikut gambaran harga terbaru tahun 2026:\n\n**Faktor yang Mempengaruhi Harga:**\n\n**1. Lokasi**\nLokasi strategis seperti jalan protokol Sudirman-Thamrin, tol dalam kota, atau kawasan bisnis SCBD memiliki harga sewa lebih tinggi dibandingkan kawasan pinggiran Jakarta.\n\n**2. Ukuran Billboard**\n- Ukuran 4x6 meter: Rp 15-30 juta/bulan\n- Ukuran 5x10 meter: Rp 25-50 juta/bulan\n- Ukuran 8x12 meter: Rp 40-80 juta/bulan\n\n**3. Durasi Sewa**\nSewa jangka panjang (6-12 bulan) biasanya mendapatkan diskon 10-20% dari harga normal.\n\n**4. Jenis Billboard**\nBillboard reguler (vinyl) lebih terjangkau dibandingkan billboard digital (videotron) yang bisa mencapai Rp 100-200 juta/bulan.\n\n**5. Biaya Tambahan**\n- Biaya cetak vinyl: Rp 1-3 juta\n- Biaya pemasangan: Rp 2-5 juta\n- Biaya perizinan: Rp 1-5 juta\n\n**Rekomendasi:**\nUntuk mendapatkan harga terbaik, konsultasikan kebutuhan Anda dengan PT. Jaya Makmur Kreasi. Kami menyediakan berbagai pilihan billboard di lokasi strategis Jakarta dengan harga kompetitif.",
                'category_index' => 3,
            ],
            [
                'title' => 'Cara Pasang Iklan Billboard yang Efektif untuk UMKM',
                'content' => "UMKM seringkali berpikir bahwa billboard hanya untuk perusahaan besar. Padahal, billboard bisa menjadi media promosi yang sangat efektif untuk UMKM dengan strategi yang tepat. Berikut caranya:\n\n**1. Pilih Ukuran yang Sesuai Budget**\nTidak perlu billboard super besar. Billboard ukuran 4x6 meter di lokasi yang tepat sudah cukup untuk menjangkau ribuan orang setiap hari.\n\n**2. Lokasi Strategis dengan Harga Terjangkau**\nPilih lokasi di pinggiran kota atau jalur menuju pusat perbelanjaan yang ramai. Harganya lebih terjangkau namun traffic tetap tinggi.\n\n**3. Desain yang Menarik dan Informatif**\nKarena budget terbatas, pastikan desain billboard Anda maksimal:\n- Gunakan gambar produk yang jelas\n- Sertakan kontak (WA/telepon)\n- Call-to-action yang kuat\n- Maksimal 7 kata\n\n**4. Sewa untuk Kampanye Spesifik**\nSewa billboard untuk event tertentu seperti:\n- Peluncuran produk baru\n- Promo hari raya\n- Diskon musiman\n- Grand opening\n\n**5. Ukur ROI Sederhana**\nGunakan nomor telepon khusus atau URL unik untuk melacak berapa banyak leads yang berasal dari billboard.\n\n**6. Manfaatkan Sistem Sewa Bersama**\nBeberapa penyedia jasa menawarkan sistem sewa bersama (sharing) di mana biaya sewa bisa dibagi untuk jangka waktu tertentu.\n\nJangan ragu untuk memulai. Billboard adalah investasi pemasaran jangka panjang yang memberikan exposure konsisten untuk brand UMKM Anda.",
                'category_index' => 0,
            ],
            [
                'title' => 'Jenis-Jenis Papan Reklame yang Wajib Diketahui Pebisnis',
                'content' => "Sebagai pebisnis, memahami jenis-jenis papan reklame akan membantu Anda memilih media promosi yang tepat. Berikut jenis-jenis papan reklame yang umum digunakan:\n\n**1. Billboard**\nPapan reklame berukuran besar yang dipasang permanen di struktur besi. Cocok untuk brand awareness jangka panjang. Ukuran standar: 4x6m, 5x10m, 8x12m.\n\n**2. Baliho**\nMirip billboard tapi bersifat temporer. Biasanya dipasang untuk event, pemilu, atau promosi singkat. Pemasangan lebih sederhana dan biaya lebih murah.\n\n**3. Videotron / LED Screen**\nLayar digital yang menampilkan iklan bergerak. Konten bisa diubah kapan saja. Cocok untuk promosi dinamis dengan biaya sewa lebih tinggi.\n\n**4. Neon Box**\nPapan reklame dengan pencahayaan dari dalam. Efektif 24 jam, cocok untuk identitas toko, restoran, atau brand yang ingin terlihat premium.\n\n**5. Signage**\nPapan petunjuk atau penanda lokasi usaha. Ukuran bervariasi, biasanya dipasang di depan toko atau gedung.\n\n**6. Rooftop**\nReklame yang dipasang di atas atap gedung. Visibilitas sangat luas karena posisinya yang tinggi.\n\n**7. Banner / Spanduk**\nMedia reklame sederhana dari kain atau vinyl. Pemasangan temporer, biaya murah, cocok untuk promosi jangka pendek.\n\n**8. Wall Painting**\nLukisan atau cat dinding besar di sisi gedung. Biaya lebih murah dari billboard, tapi kurang fleksibel karena tidak bisa diganti dalam waktu dekat.\n\n**9. Midpoint / Umbul-umbul**\nBendera atau panel kecil yang dipasang di tiang-tiang jalan. Cocok untuk event atau promosi properti.\n\nSetiap jenis reklame memiliki kelebihan masing-masing. Konsultasikan dengan PT. Jaya Makmur Kreasi untuk menentukan media yang paling sesuai dengan kebutuhan dan budget Anda.",
                'category_index' => 3,
            ],
            [
                'title' => 'Biaya dan Prosedur Perizinan Reklame Outdoor di Indonesia',
                'content' => "Perizinan adalah aspek krusial dalam pemasangan reklame outdoor. Tanpa izin yang lengkap, Anda berisiko terkena sanksi berupa denda hingga pembongkaran paksa. Berikut panduan lengkapnya:\n\n**Jenis Izin yang Diperlukan:**\n\n**1. Izin Reklame (Izinke)**\nDikeluarkan oleh Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu (DPMPTSP) setempat. Mencakup:\n- Lokasi pemasangan\n- Ukuran dan jenis reklame\n- Durasi izin\n\n**2. Izin Gangguan (HO)**\nUntuk reklame yang dipasang di lahan tertentu, diperlukan izin dari kelurahan/kecamatan.\n\n**3. Perjanjian Sewa Lahan**\nJika billboard berdiri di lahan pribadi, diperlukan surat perjanjian dengan pemilik lahan.\n\n**Prosedur Pengurusan Izin:**\n1. Mengajukan permohonan ke DPMPTSP\n2. Melampirkan:\n   - KTP dan NPWP\n   - Akta perusahaan\n   - Desain reklame\n   - Surat pernyataan lokasi\n3. Verifikasi dan survei lokasi oleh petugas\n4. Pembayaran retribusi daerah\n5. Penerbitan izin\n\n**Biaya Retribusi Reklame:**\nBiaya dihitung berdasarkan:\n- Nilai Strategis Lokasi (NSL)\n- Ukuran reklame\n- Jenis reklame\n- Durasi\n\nEstimasi biaya retribusi untuk billboard ukuran 4x6m di Jakarta: Rp 5-15 juta/tahun.\n\n**Sanksi Pelanggaran:**\n- Denda administratif: 2-5 kali lipat retribusi\n- Pembongkaran paksa\n- Pencabutan izin usaha\n\nUntuk kemudahan perizinan, percayakan pada PT. Jaya Makmur Kreasi. Kami mengurus seluruh perizinan reklame Anda secara profesional.",
                'category_index' => 3,
            ],
            [
                'title' => 'Desain Billboard yang Efektif: Panduan untuk Pemula',
                'content' => "Desain billboard yang efektif adalah kunci kesuksesan kampanye iklan outdoor. Karena billboard hanya terlihat dalam hitungan detik, desain harus mampu menyampaikan pesan dengan cepat dan jelas. Berikut panduannya:\n\n**1. Prinsip 3 Detik**\nRata-rata orang hanya melihat billboard selama 3-5 detik. Pesan harus langsung tertangkap dalam waktu tersebut.\n\n**2. Gunakan Teks Minimal**\nMaksimal 7-10 kata. Jika terlalu banyak teks, pesan tidak akan terbaca. Ingat: billboard BUKAN brosur.\n\n**3. Kontras Tinggi**\nGunakan kombinasi warna kontras untuk memastikan keterbacaan dari jarak jauh. Contoh: teks putih di latar gelap, atau teks hitam di latar terang.\n\n**4. Font Besar dan Jelas**\nGunakan font sans-serif yang tebal (bold). Hindari font dekoratif yang sulit dibaca. Ukuran font minimal 10% dari tinggi billboard.\n\n**5. Visual yang Kuat**\nGunakan gambar produk atau visual yang relevan. Hindari gambar terlalu ramai. Satu visual utama sudah cukup.\n\n**6. Call-to-Action Jelas**\nSertakan ajakan bertindak: \"Hubungi 0811-xxxx\", \"Kunjungi toko kami\", atau \"Scan QR code\".\n\n**7. Branding Konsisten**\nPastikan logo dan warna brand konsisten dengan identitas perusahaan di media lain.\n\n**8. Uji Keterbacaan**\nCetak desain dalam ukuran kecil (A4) dan lihat dari jarak 3 meter. Jika terbaca, maka desain siap untuk billboard ukuran besar.\n\n**Contoh Desain Efektif:**\n- [Logo] di pojok\n- Gambar produk (70% area)\n- Teks: 3-5 kata (15% area)\n- CTA: kontak atau website (15% area)\n\nButuh bantuan desain billboard? PT. Jaya Makmur Kreasi siap membantu Anda membuat desain reklame yang menarik dan efektif.",
                'category_index' => 2,
            ],
            [
                'title' => 'Keunggulan Videotron Dibanding Media Iklan Konvensional',
                'content' => "Videotron atau billboard digital semakin populer dalam industri periklanan outdoor. Dibandingkan media iklan konvensional seperti billboard cetak atau baliho, videotron menawarkan berbagai keunggulan:\n\n**1. Konten Dinamis**\nTidak terbatas pada satu gambar statis. Videotron dapat menampilkan video, animasi, dan konten bergerak yang lebih menarik perhatian.\n\n**2. Update Real-Time**\nKonten dapat diubah kapan saja tanpa biaya cetak. Cocok untuk:\n- Promosi flash sale\n- Update informasi实时\n- Iklan bergilir (multiple ads)\n\n**3. Jadwal Terprogram**\nIklan dapat dijadwalkan berdasarkan:\n- Waktu (pagi/siang/malam)\n- Hari (weekday/weekend)\n- Cuaca dan kondisi lainnya\n\n**4. Engagement Lebih Tinggi**\nKonten bergerak dan video meningkatkan recall rate hingga 40% dibanding iklan statis.\n\n**5. Multi-Advertiser**\nSatu videotron bisa menampilkan beberapa iklan secara bergilir, sehingga biaya sewa lebih terjangkau.\n\n**6. Analytics & Reporting**\nBeberapa videotron modern menyediakan data:\n- Jumlah penayangan\n- Durasi tayang\n- Performance report\n\n**7. Ramah Lingkungan**\nTidak ada limbah cetak vinyl. Satu videotron menggantikan ratusan cetakan billboard konvensional per tahun.\n\n**Kekurangan Videotron:**\n- Biaya sewa lebih tinggi (Rp 50-200 juta/bulan)\n- Biaya produksi konten video\n- Keterbatasan lokasi (belum sebanyak billboard konvensional)\n\nVideotron adalah investasi yang sangat efektif untuk brand yang ingin tampil modern, dinamis, dan kompetitif di era digital.",
                'category_index' => 1,
            ],
            [
                'title' => 'Tips Memilih Jasa Penyedia Reklame Terpercaya',
                'content' => "Memilih jasa penyedia reklame yang tepat sangat penting untuk memastikan kampanye iklan Anda berjalan sukses. Berikut tips memilih penyedia reklame terpercaya:\n\n**1. Cek Portofolio**\nLihat portofolio proyek-proyek sebelumnya. Penyedia yang baik memiliki portofolio beragam dengan klien dari berbagai industri.\n\n**2. Legalitas Perusahaan**\nPastikan perusahaan memiliki:\n- Akta pendirian\n- NPWP\n- SIUP/NIB\n- Terdaftar di kementerian terkait\n\n**3. Lokasi Billboard Strategis**\nPenyedia terpercaya memiliki database lokasi billboard lengkap dengan detail:\n- Foto lokasi\n- Data lalu lintas\n- Visibilitas\n- Status perizinan\n\n**4. Pelayanan Lengkap**\nPilih penyedia yang menawarkan layanan end-to-end:\n- Konsultasi lokasi\n- Desain\n- Produksi\n- Pemasangan\n- Perawatan\n- Perizinan\n\n**5. Testimoni dan Review**\nCari testimoni dari klien sebelumnya. Penyedia yang baik memiliki banyak review positif dan hubungan jangka panjang dengan klien.\n\n**6. Harga Transparan**\nHindari penyedia yang tidak memberikan rincian biaya secara jelas. Harga sewa, biaya produksi, dan biaya perizinan harus dijelaskan secara transparan.\n\n**7. Dukungan Teknis**\nPastikan penyedia menyediakan dukungan teknis selama masa sewa, termasuk perawatan billboard dan penggantian lampu jika diperlukan.\n\n**8. Jaringan Luas**\nPenyedia dengan jaringan luas di berbagai kota memberikan fleksibilitas untuk ekspansi kampanye ke daerah lain.\n\nPT. Jaya Makmur Kreasi memenuhi semua kriteria di atas. Kami telah berpengalaman melayani berbagai klien dari berbagai sektor industri. Hubungi kami untuk konsultasi gratis!",
                'category_index' => 0,
            ],
            [
                'title' => 'Pemasangan Neon Box untuk Toko: Meningkatkan Visibilitas Bisnis',
                'content' => "Neon box adalah solusi reklame yang sempurna untuk toko, restoran, dan usaha retail. Dengan pencahayaan yang terang dan desain yang menarik, neon box mampu meningkatkan visibilitas bisnis Anda secara signifikan. Berikut manfaat dan tips pemasangannya:\n\n**Manfaat Neon Box untuk Toko:**\n\n**1. Visibilitas 24 Jam**\nNeon box tetap terlihat jelas di malam hari, memastikan toko Anda selalu terbaca oleh calon pelanggan.\n\n**2. Kesan Profesional**\nToko dengan neon box terlihat lebih profesional dan premium dibandingkan dengan spanduk biasa.\n\n**3. Brand Recognition**\nDesain neon box yang konsisten dengan logo brand meningkatkan brand recognition di benak konsumen.\n\n**4. Tahan Lama**\nNeon box LED modern memiliki umur hingga 50.000 jam dengan perawatan minimal.\n\n**5. Hemat Listrik**\nTeknologi LED sangat efisien, biaya listrik hanya Rp 50-200 ribu per bulan tergantung ukuran.\n\n**Tips Memilih Neon Box:**\n\n**1. Ukuran Sesuai Lokasi**\nSesuaikan ukuran neon box dengan lebar fasad toko. Idealnya, neon box minimal 60-80% dari lebar toko.\n\n**2. Warna Kontras**\nPilih kombinasi warna yang kontras dengan background bangunan agar mudah terbaca dari jauh.\n\n**3. Pencahayaan Optimal**\nGunakan LED dengan kecerahan yang cukup. Neon box yang terlalu redup akan sia-sia.\n\n**4. Material Berkualitas**\nPilih acrylic berkualitas tinggi yang tidak mudah menguning terkena sinar matahari.\n\n**5. Izin Pemasangan**\nPastikan pemasangan neon box sudah sesuai peraturan daerah setempat.\n\n**Estimasi Biaya Neon Box:**\n- Ukuran 50x100cm: Rp 1-2 juta\n- Ukuran 100x150cm: Rp 3-5 juta\n- Ukuran custom besar: Rp 5-15 juta\n\nPasang neon box di toko Anda dan rasakan perbedaan visibilitas bisnis yang signifikan!",
                'category_index' => 2,
            ],
            [
                'title' => 'Cara Hitung ROI Iklan Billboard untuk Bisnis Anda',
                'content' => "ROI (Return on Investment) adalah metrik penting untuk mengukur efektivitas kampanye billboard Anda. Berikut cara menghitungnya:\n\n**Rumus Dasar ROI:**\nROI = (Keuntungan - Biaya) / Biaya x 100%\n\n**Langkah-Langkah Menghitung ROI Billboard:**\n\n**1. Hitung Total Biaya**\nKomponen biaya billboard:\n- Biaya sewa: Rp 15-50 juta/bulan\n- Biaya cetak vinyl: Rp 1-3 juta\n- Biaya pemasangan: Rp 2-5 juta\n- Biaya perizinan: Rp 1-5 juta\n- Biaya desain: Rp 500rb - 2 juta\n\n**2. Tentukan Tujuan Kampanye**\n- Brand awareness: ukur melalui peningkatan search volume dan social media mentions\n- Penjualan: hitung penjualan yang dikaitkan dengan iklan billboard\n- Traffic toko: hitung peningkatan pengunjung\n\n**3. Gunakan Tracking Method**\n- URL khusus: buat landing page spesifik untuk billboard\n- QR code: lacak berapa banyak scan\n- Nomor telepon khusus: gunakan nomor berbeda untuk billboard\n- Kode promo: kode diskon eksklusif billboard\n\n**4. Hitung Selisih Sebelum-Sesudah**\nBandingkan metrik bisnis 3 bulan sebelum dan 3 bulan selama kampanye billboard.\n\n**5. Contoh Perhitungan Sederhana:**\nBiaya kampanye: Rp 60 juta (3 bulan sewa + produksi)\nPeningkatan penjualan: Rp 180 juta\nROI = (180.000.000 - 60.000.000) / 60.000.000 x 100% = 200%\n\nArtinya, setiap Rp 1 yang dikeluarkan menghasilkan Rp 3 pendapatan.\n\n**Rata-Rata ROI Billboard:**\nBerdasarkan survei industri, billboard memberikan rata-rata ROI 150-400% untuk kampanye yang tepat sasaran.\n\n**Tips Meningkatkan ROI:**\n- Pilih lokasi yang tepat\n- Desain yang efektif\n- Call-to-action yang jelas\n- Integrasi dengan kanal digital\n\nKonsultasikan strategi billboard Anda dengan PT. Jaya Makmur Kreasi untuk memaksimalkan ROI kampanye iklan outdoor Anda.",
                'category_index' => 3,
            ],
        ];

        Post::withTrashed()->get()->each->forceDelete();

        foreach ($posts as $i => $postData) {
            $categoryId = $postCategories[$postData['category_index'] % $postCategories->count()];

            Post::create([
                'author_id' => $author->id,
                'category_id' => $categoryId,
                'title' => $postData['title'],
                'content_body' => $postData['content'],
                'status' => 'published',
                'published_at' => now()->subDays(count($posts) - $i),
            ]);
        }
    }
}
