<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreAdvertisingPointRequest;
use App\Models\AdvertisingPoint;
use App\Models\Category;
use App\Services\ImageOptimizationService;
use App\Services\SeoService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;

class AdvertisingPointController extends Controller
{
    public function __construct(
        private ImageOptimizationService $imageService,
        private SeoService $seoService
    ) {
        $this->middleware(['auth', 'role:admin|super-admin|editor']);
    }

    public function index(Request $request): View
    {
        $query = AdvertisingPoint::with('category')->latest();

        if ($request->filled('search')) {
            $query->where(function ($q) use ($request) {
                $q->where('title', 'like', "%{$request->search}%")
                    ->orWhere('location_name', 'like', "%{$request->search}%")
                    ->orWhere('city', 'like', "%{$request->search}%");
            });
        }

        if ($request->filled('city')) {
            $query->where('city', $request->city);
        }

        if ($request->filled('status')) {
            $query->where('status', $request->status);
        }

        if ($request->filled('category_id')) {
            $query->where('category_id', $request->category_id);
        }

        $points = $query->paginate(15)->withQueryString();
        $cities = AdvertisingPoint::distinct()->pluck('city')->sort()->values();
        $categories = Category::byType('product')->active()->get();
        $stats = [
            'total' => AdvertisingPoint::count(),
            'available' => AdvertisingPoint::available()->count(),
            'booked' => AdvertisingPoint::where('status', 'booked')->count(),
        ];

        return view('admin.advertising-points.index', compact('points', 'cities', 'categories', 'stats'));
    }

    public function create(): View
    {
        $categories = Category::byType('product')->active()->get();
        $seo = $this->seoService->forPage('Tambah Titik Reklame')->render();

        return view('admin.advertising-points.create', compact('categories', 'seo'));
    }

    public function store(StoreAdvertisingPointRequest $request): RedirectResponse
    {
        $data = $request->validated();

        // Handle thumbnail upload
        if ($request->hasFile('thumbnail')) {
            $images = $this->imageService->process(
                $request->file('thumbnail'),
                'advertising-points',
                $request->input('slug')
            );
            $data['thumbnail'] = $images['original'];
            $data['og_image'] = $images['og'];
        }

        // Handle gallery uploads
        if ($request->hasFile('gallery')) {
            $gallery = [];
            foreach ($request->file('gallery') as $index => $file) {
                $images = $this->imageService->process(
                    $file,
                    'advertising-points/gallery',
                    $request->input('slug') . '-' . $index
                );
                $gallery[] = $images['original'];
            }
            $data['gallery'] = $gallery;
        }

        // Handle OG image upload
        if ($request->hasFile('og_image')) {
            $images = $this->imageService->process(
                $request->file('og_image'),
                'advertising-points/og',
                $request->input('slug') . '-og'
            );
            $data['og_image'] = $images['og'];
        }

        // JSON-LD will be auto-generated by model boot
        $point = AdvertisingPoint::create($data);

        return redirect()
            ->route('admin.advertising-points.index')
            ->with('success', "Titik reklame '{$point->title}' berhasil ditambahkan.");
    }

    public function show(AdvertisingPoint $advertisingPoint): View
    {
        $advertisingPoint->load('category', 'inquiries');
        $seo = $this->seoService->forModel($advertisingPoint)->render();

        return view('admin.advertising-points.show', compact('advertisingPoint', 'seo'));
    }

    public function edit(AdvertisingPoint $advertisingPoint): View
    {
        $categories = Category::byType('product')->active()->get();
        $seo = $this->seoService->forPage('Edit: ' . $advertisingPoint->title)->render();

        return view('admin.advertising-points.edit', compact('advertisingPoint', 'categories', 'seo'));
    }

    public function update(StoreAdvertisingPointRequest $request, $id): RedirectResponse
    {
        $advertisingPoint = AdvertisingPoint::withTrashed()->findOrFail($id);

        $data = $request->validated();

        // Handle thumbnail upload
        if ($request->hasFile('thumbnail')) {
            if ($advertisingPoint->thumbnail) {
                $this->imageService->delete('advertising-points', $advertisingPoint->slug);
            }
            $images = $this->imageService->process(
                $request->file('thumbnail'),
                'advertising-points',
                $request->input('slug')
            );
            $data['thumbnail'] = $images['original'];
            $data['og_image'] = $images['og'];
        }

        // Handle gallery uploads
        if ($request->hasFile('gallery')) {
            if (!empty($advertisingPoint->gallery)) {
                foreach ($advertisingPoint->gallery as $oldImg) {
                    $this->imageService->delete('advertising-points/gallery', basename($oldImg, '.' . pathinfo($oldImg, PATHINFO_EXTENSION)));
                }
            }
            $gallery = [];
            foreach ($request->file('gallery') as $index => $file) {
                $images = $this->imageService->process(
                    $file,
                    'advertising-points/gallery',
                    $request->input('slug') . '-' . $index
                );
                $gallery[] = $images['original'];
            }
            $data['gallery'] = $gallery;
        }

        // Handle OG image upload
        if ($request->hasFile('og_image')) {
            $images = $this->imageService->process(
                $request->file('og_image'),
                'advertising-points/og',
                $request->input('slug') . '-og'
            );
            $data['og_image'] = $images['og'];
        }

        $advertisingPoint->update($data);

        return redirect()
            ->route('admin.advertising-points.index')
            ->with('success', "Titik reklame '{$advertisingPoint->title}' berhasil diperbarui.");
    }

    public function bulkDestroy(Request $request): RedirectResponse
    {
        $request->validate(['ids' => ['required', 'array'], 'ids.*' => ['integer']]);
        $points = AdvertisingPoint::whereIn('id', $request->ids)->get();
        $count = 0;
        foreach ($points as $point) {
            if ($point->thumbnail) {
                $this->imageService->delete('advertising-points', $point->slug);
            }
            if ($point->og_image) {
                $ogPath = pathinfo($point->og_image, PATHINFO_DIRNAME);
                $ogFilename = pathinfo($point->og_image, PATHINFO_FILENAME);
                $this->imageService->delete($ogPath, $ogFilename);
            }
            if (!empty($point->gallery)) {
                foreach ($point->gallery as $img) {
                    $galPath = pathinfo($img, PATHINFO_DIRNAME);
                    $galFilename = pathinfo($img, PATHINFO_FILENAME);
                    $this->imageService->delete($galPath, $galFilename);
                }
            }
            $point->forceDelete();
            $count++;
        }
        return redirect()->back()->with('success', "$count titik reklame berhasil dihapus.");
    }

    public function destroy(AdvertisingPoint $advertisingPoint): RedirectResponse
    {
        if ($advertisingPoint->thumbnail) {
            $this->imageService->delete('advertising-points', $advertisingPoint->slug);
        }

        if ($advertisingPoint->og_image) {
            $ogPath = pathinfo($advertisingPoint->og_image, PATHINFO_DIRNAME);
            $ogFilename = pathinfo($advertisingPoint->og_image, PATHINFO_FILENAME);
            $this->imageService->delete($ogPath, $ogFilename);
        }

        if (!empty($advertisingPoint->gallery)) {
            foreach ($advertisingPoint->gallery as $img) {
                $galPath = pathinfo($img, PATHINFO_DIRNAME);
                $galFilename = pathinfo($img, PATHINFO_FILENAME);
                $this->imageService->delete($galPath, $galFilename);
            }
        }

        $advertisingPoint->forceDelete();

        return redirect()
            ->route('admin.advertising-points.index')
            ->with('success', 'Titik reklame berhasil dihapus secara permanen.');
    }

    public function toggleStatus(AdvertisingPoint $advertisingPoint): RedirectResponse
    {
        $newStatus = $advertisingPoint->status === 'available' ? 'booked' : 'available';
        $advertisingPoint->update(['status' => $newStatus]);

        return redirect()
            ->back()
            ->with('success', "Status diubah menjadi: {$advertisingPoint->status_label}");
    }
}
